//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TShop.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class QUYENHANTHANHVIEN
    {
        public int MaTV { get; set; }
        public int MaQ { get; set; }
        public string GhiChu { get; set; }
    
        public virtual QUYENHAN QUYENHAN { get; set; }
        public virtual THANHVIEN THANHVIEN { get; set; }
    }
}
